# Generated by Django 3.0.3 on 2020-07-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='image',
        ),
    ]
