# Generated by Django 3.0.3 on 2020-09-24 04:53

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
