# Generated by Django 3.0.3 on 2020-09-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0005_auto_20200924_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='icon',
        ),
    ]
