# Generated by Django 3.0.3 on 2020-09-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0006_remove_edit_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='body',
        ),
    ]
