# Generated by Django 3.0.3 on 2020-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0007_remove_edit_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
